---
- name: Add {{ cloudwatch_package }} key
  rpm_key:
    state: present
    key: "{{ cloudwatch_package_gpg }}"
  tags:
    - add-key
    - download
    - install

- name: Download {{ cloudwatch_package }}.rpm.sig
  get_url:
    url: "{{ cloudwatch_package_signature }}"
    dest: "{{ temp_path }}/{{ cloudwatch_package }}.rpm.sig"
    force: true
  retries: 2
  delay: 3
  tags:
    - download-signature
    - verify-signature
    - download
    - install

- name: Download {{ cloudwatch_package }}.rpm
  get_url:
    url: "{{ cloudwatch_package_url }}"
    dest: "{{ temp_path }}/{{ cloudwatch_package }}.rpm"
    force: true
  retries: 2
  delay: 3
  tags:
    - download
    - verify-signature
    - install

- name: Verify {{ cloudwatch_package }} package signature
  command: gpg --verify {{ cloudwatch_package }}.rpm.sig {{ cloudwatch_package }}.rpm
  register: verified_sig
  failed_when: "'BAD' in verified_sig.stderr"
  changed_when: false
  args:
    chdir: "{{ temp_path }}"
  tags:
    - verify-signature
    - install

- name: Install {{ cloudwatch_package }} dependencies packages
  yum:
    name: "{{ dependencies_packages }}"
    state: present
  tags:
    - install

- name: Install {{ cloudwatch_package }}.rpm
  yum:
    name: "{{ temp_path }}/{{ cloudwatch_package }}.rpm"
    state: present
  tags:
    - install
