---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Add {{ cloudwatch_package }} key
  apt_key:
    state: present
    url: "{{ cloudwatch_package_gpg }}"

- name: Download {{ cloudwatch_package }}.deb.sig
  get_url:
    url: "{{ cloudwatch_package_url }}"
    dest: "{{ temp_path }}/{{ cloudwatch_package }}.deb.sig"
    force: true

- name: Download {{ cloudwatch_package }}.deb
  get_url:
    url: "{{ cloudwatch_package_url }}"
    dest: "{{ temp_path }}/{{ cloudwatch_package }}.deb"
    force: true

- name: Verify {{ cloudwatch_package }} package signature
  shell: gpg --verify {{ cloudwatch_package }}.deb.sig {{ cloudwatch_package }}.deb
  register: verified_sig
  failed_when: "'BAD' in verified_sig.stderr"
  changed_when: false
  args:
    executable: /bin/bash
    chdir: "{{ temp_path }}"

- name: Install {{ cloudwatch_package }}.deb
  apt:
    deb: "{{ temp_path }}/{{ cloudwatch_package }}.deb"
    state: latest
