---
- name: Add {{ cloudwatch_package }} key
  rpm_key:
    state: present
    key: "{{ cloudwatch_package_gpg }}"

- name: Download {{ cloudwatch_package }}.rpm.sig
  get_url:
    url: "{{ cloudwatch_package_signature }}"
    dest: "{{ temp_path }}/{{ cloudwatch_package }}.rpm.sig"
    force: true

- name: Download {{ cloudwatch_package }}.rpm
  get_url:
    url: "{{ cloudwatch_package_url }}"
    dest: "{{ temp_path }}/{{ cloudwatch_package }}.rpm"
    force: true

- name: verify {{ cloudwatch_package }} package signature
  shell: gpg --verify {{ cloudwatch_package }}.rpm.sig {{ cloudwatch_package }}.rpm
  register: verified_sig
  failed_when: "'BAD' in verified_sig.stderr"
  changed_when: false
  args:
    executable: /bin/bash
    chdir: "{{ temp_path }}"

- name: Install {{ cloudwatch_package }}.rpm
  yum:
    name: "{{ temp_path }}/{{ cloudwatch_package }}.rpm"
    state: latest
