---
- name: add {{ cloudwatch_package }} key
  rpm_key:
    state: present
    key: "{{ cloudwatch_package_gpg }}"

- name: download {{ cloudwatch_package }}.rpm.sig
  get_url:
    url: "{{ cloudwatch_package_url }}"
    dest: "/{{ temp_path }}/{{ cloudwatch_package }}.rpm.sig"
  changed_when: false

- name: download {{ cloudwatch_package }}.rpm
  get_url:
    url: "{{ cloudwatch_package_url }}"
    dest: "/{{ temp_path }}/{{ cloudwatch_package }}.rpm"
  changed_when: false

- name: verify {{ cloudwatch_package }} package signature
  shell: gpg --verify {{ cloudwatch_package }}.rpm.sig {{ cloudwatch_package }}.rpm
  register: verified_sig
  failed_when: "'BAD' in verified_sig.stderr"
  changed_when: false
  args:
    executable: /bin/bash
    chdir: /{{ temp_path }}

- name: install {{ cloudwatch_package }} rpm
  yum:
    name: "/{{ temp_path }}/{{ cloudwatch_package }}.rpm"
    state: latest

- name: remove downloaded {{ cloudwatch_package }}.rpm.sig
  file:
    path: "/{{ temp_path }}/{{ cloudwatch_package }}.rpm.sig"
    state: absent
  changed_when: false

- name: remove downloaded {{ cloudwatch_package }}.rpm
  file:
    path: "/{{ temp_path }}/{{ cloudwatch_package }}.rpm"
    state: absent
  changed_when: false
