---
- name: Start {{ cwa_package }}
  command: "{{ cwa_agent_ctl }} -a start"

- name: Stop {{ cwa_package }}
  command: "{{ cwa_agent_ctl }} -a stop"

- name: Reload {{ cwa_package }}
  command: "{{ cwa_agent_ctl }} -a fetch-config -m {{ cwa_agent_mode }} -c file:{{ cwa_agent_config_file }} -s"
