---
- name: Start {{ cloudwatch_package }}
  command: "{{ cloudwatch_agent_ctl }} -a start"

- name: Stop {{ cloudwatch_package }}
  command: "{{ cloudwatch_agent_ctl }} -a stop"

- name: Reload {{ cloudwatch_package }}
  command: "{{ cloudwatch_agent_ctl }} -a fetch-config -m {{ agent_mode }} -c file:{{ cloudwatch_agent_config_file }} -s"
