---
- name: Start {{ cwa_package }}
  command: "{{ cwa_agent_ctl }} -a start"
  when: >
    ansible_virtualization_type != 'lxc' or
    ansible_virtualization_type != 'docker' or
    ansible_virtualization_type is not defined

- name: Stop {{ cwa_package }}
  command: "{{ cwa_agent_ctl }} -a stop"
  when: >
    ansible_virtualization_type != 'lxc' or
    ansible_virtualization_type != 'docker' or
    ansible_virtualization_type is not defined

- name: Reload {{ cwa_package }}
  command: "{{ cwa_agent_ctl }} -a fetch-config -m {{ cwa_agent_mode }} -c file:{{ cwa_agent_config_file }} -s"
  when: >
    ansible_virtualization_type != 'lxc' or
    ansible_virtualization_type != 'docker' or
    ansible_virtualization_type is not defined

- name: Reload {{ cwa_logrotate_daemon }}
  command: "{{ cwa_logrotate_daemon }} -d {{ cwa_logrotate_config_file }}"
  when: >
    ansible_virtualization_type != 'lxc' or
    ansible_virtualization_type != 'docker' or
    ansible_virtualization_type is not defined
