---
- name: Prepare
  hosts: all
  gather_facts: true

  tasks:
    - name: Install CentOS 7 repository on RedHat 7 to avoid Subscription Manager dependencies
      yum_repository:
        name: base
        description: CentOS-7 - Base
        file: CentOS-Base.repo
        baseurl: http://mirror.centos.org/centos/7/os/$basearch/
        enabled: yes
        gpgcheck: no
      when: >
        ansible_os_family == 'RedHat' and
        ansible_distribution == 'RedHat' and
        ansible_distribution_major_version == '7'
